name: Import publications from BibTeX

on:
  push:
    paths:
      - 'data/bibliography/publications.bib'
      - 'scripts/bibtex_to_publications.py'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install bibtexparser python-slugify

      - name: Import from BibTeX
        run: python scripts/bibtex_to_publications.py

      - name: Auto-commit generated publications
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pub): import publications from BibTeX"
          file_pattern: content/publication/**
